package com.thousand.bus.global.service

object Endpoints {

    const val REGISTRATION = "/api/v1/profile/register"
    const val AUTH = "/api/v1/profile/loginByToken"
    const val LOGIN = "/api/v1/profile/login"
    const val CONFIRMATION = "/api/v1/profile/confirmation"
    const val ADD_BUS = "/api/v1/profile/addCar"
    const val SEND_FEEDBACK = "/api/v1/toFeedback"
    const val CAR_LIST = "/api/v1/profile/cars"
    const val CAR_TYPE = "/api/v1/carTypes"
    const val STATIONS = "/api/v1/stations"
    const val CITY = "/api/v1/cities"
    const val TRAVEL_LIST = "/api/v1/travel/list"
    const val TRAVEL_SHOW = "/api/v1/travel/show"
    const val TRAVEL_CREATE = "/api/v1/travel/add"
    const val TRAVEL_UPCOMING = "api/v1/profile/carTravels"
    const val TRAVEL_HISTORY = "/api/v1/travel/histories"
    const val PASSENGERS = "/api/v1/travel/my-passengers"
    const val FEEDBACK_LIST = "/api/v1/feedback/list"
    const val PLACE_EDIT = "/api/v1/travel/place/edit"
    const val STATIONS_BETWEEN_CITY = "/api/v1/travel-stations"
    const val BECOME_PASSENGER = "/api/v1/profile/role/passenger"
    const val BECOME_DRIVER = "/api/v1/profile/role/driver"
    const val PROFILE_EDIT = "/api/v1/profile/edit"
    const val TERMS_AND_POLICY = "/api/v1/setting"
    const val RESERVATION = "/api/v1/travel/place/reservation"
    const val ROLE_PASSENGER = "/api/v1/profile/role/passenger"
    const val ROLE_DRIVER = "/api/v1/profile/role/driver"
    const val MY_TICKETS = "/api/v1/my-tickets-new"
    const val SMS_CONFIRM = "/api/v1/profile/phone-confirmation"
    const val PASSWORD_RESTORE_SEND_SMS = "/api/v1/profile/password-reset/send"
    const val PASSWORD_RESTORE = "/api/v1/profile/password-reset/check"
    const val TAKE_BACK_TICKET = "/api/v1/travel/place/cancel"
    const val DELETE_TRAVEL = "/api/v1/travel/delete"
    const val CLIENT_ORDER_HISTORY = "/api/v1/order-histories"
    const val LOGOUT = "/api/v1/profile/logout"

}